### ISSUE TITLE
It is there a CLI?

### ISSUE THREAD

**Issue by yeikel** [ruzicka/to-json-schema#2]
Hi, 

I'd like to define a JSON file such as 

```
{
 "user" : "sample"
}
```

And save it as `user.json `and then run something such as `to-json-schema users.json userschema.json` in order to create a schema file for the `users.json `file

**Comment by ruzicka** [comment]
That might be a nice feature. Maybe sometime later if I find some time, but currently I'm not planning to include CLI.
