### ISSUE TITLE
Fails to find the schema for an array of arrays when one array is empty

### ISSUE THREAD

**Issue by forivall** [ruzicka/to-json-schema#7]
See test case here: https://github.com/ruzicka/to-json-schema/compare/master...forivall:forivall%2Ftest-array-of-arrays?diff=unified

If i add a string to the second array (like `[['foo'], ['bar']]`), then the test case passes. As is, the generated schema is:

```json
{
  "type": "array",
  "items": {
    "type": "array"
  }
}
```

**Comment by ruzicka** [comment]
Hey @forivall ! That's an interesting case there. It would be quite complicated to modify the code to work like that. Most importantly though, I'm not quite convinced that we can make the assumption that empty arrays might be interpreted as having items of specific type based on existence of a different array. I think that the parser is actually doing a good job by finding specification broad enough to encompass both array items.
